version: "3.9"

services:
  rag-app:
    image: python:3.10-slim 
    container_name: ppa_rag_app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    volumes:
      - .:/app      
      - ./docs:/app/docs
      - ./vectordb:/app/vectordb
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama   # 👈 imagem ollama com curl
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ollama_models:/root/.ollama
    restart: always

volumes:
  ollama_models:
