services:
  rag-app:
    build: .
    container_name: ppa_rag_app
    ports:
      - "8501:8501"
    volumes:
      - ./docs:/app/docs
      - ./vectordb:/app/vectordb
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh 
      - ollama_models:/root/.ollama
    entrypoint: ["/bin/sh", "/entrypoint.sh"] 
    restart: always

volumes:
  ollama_models:
